import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { randomUUID } from 'crypto';
import { mkdir, unlink, writeFile } from 'fs/promises';
import { basename, join, resolve } from 'path';
import { SaveMeta, StorageService, StoredFile } from './storage.service';

/**
 * Local disk driver. The ONLY file in the media stack permitted to import `fs`.
 *
 * Durability caveat, stated rather than assumed: the API runs on the host while
 * only Postgres is containerised, so these files live on the host filesystem and
 * survive an API restart. They do NOT survive a container rebuild, a fresh
 * deploy onto new infrastructure, or a second API instance behind a load
 * balancer - each would have its own empty uploads directory. See the Phase 1b
 * report; this is an open hosting question, not a solved one.
 */
@Injectable()
export class LocalDiskStorageService extends StorageService {
  private readonly logger = new Logger(LocalDiskStorageService.name);
  private readonly root: string;
  private readonly publicPrefix: string;

  constructor(config: ConfigService) {
    super();
    this.root = resolve(config.get<string>('UPLOAD_DIR') ?? 'uploads');
    this.publicPrefix = config.get<string>('UPLOAD_PUBLIC_PREFIX') ?? '/api/uploads';
  }

  async save(buffer: Buffer, meta: SaveMeta): Promise<StoredFile> {
    // UUID, never the uploaded filename. Two reasons: collisions, and the fact
    // that an attacker-supplied name is the raw material for path traversal.
    // Sharded one level by the first two characters so a single directory does
    // not accumulate every asset the site will ever have.
    const id = randomUUID();
    const shard = id.slice(0, 2);
    const storagePath = `${shard}/${id}.${meta.extension}`;

    const dir = join(this.root, shard);
    await mkdir(dir, { recursive: true });
    await writeFile(join(this.root, storagePath), buffer);

    return { storagePath, url: `${this.publicPrefix}/${storagePath}` };
  }

  async delete(storagePath: string): Promise<void> {
    const target = this.safeResolve(storagePath);
    if (!target) {
      this.logger.warn(`Refused to delete a path outside the upload root: ${storagePath}`);
      return;
    }
    try {
      await unlink(target);
    } catch (err: any) {
      // Idempotent by contract - a missing file is the desired end state.
      if (err?.code !== 'ENOENT') throw err;
    }
  }

  /**
   * Defence in depth. storagePath is generated by save() and never client-
   * supplied, but a stored value could still be wrong after a bad migration, and
   * unlink() on an arbitrary path is not a mistake worth being one bug away
   * from. Resolves and confirms containment before returning.
   */
  private safeResolve(storagePath: string): string | null {
    if (!storagePath || storagePath.includes('\0')) return null;
    const target = resolve(this.root, storagePath);
    const rootWithSep = this.root.endsWith('/') ? this.root : `${this.root}/`;
    if (!target.startsWith(rootWithSep)) return null;
    if (basename(target).startsWith('.')) return null;
    return target;
  }
}
